# CI on Windows via appveyor
# Adapted (minorly) from xarray's appveyor.yml, which itself
# was based on Olivier Grisel's python-appveyor-demo

environment:

  matrix:
    - PYTHON: "C:\\Python36-conda64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_ENV: "py36"

install:
  # Install miniconda Python
  - "powershell ./ci/install_python.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # install xarray and depenencies
  - "conda --version"
  - "conda list"
  - "conda env create -f ./environments/dl_windows.yml"
  - "activate dl"
  - "conda list"
  - "python ./ci/dl_test.py"

test_script:
  - "pytest"
  
 
  
  
 
